# Generated by Django 5.0.1 on 2024-01-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venda', '0002_remove_venda_gastosaquinho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto_custos_base',
            name='Caixinha',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='venda',
            name='gastoCaixinha',
            field=models.FloatField(default=0.0),
        ),
    ]
