# Generated by Django 5.0.1 on 2024-02-04 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venda', '0003_produto_custos_base_caixinha_venda_gastocaixinha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('gender', models.BooleanField(default=0)),
                ('shoeUnits', models.IntegerField(default=0)),
                ('gloveUnits', models.IntegerField(default=0)),
                ('denUnits', models.IntegerField(default=0)),
                ('tiaraUnits', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Product_Base_Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Weaving', models.FloatField()),
                ('Close', models.FloatField()),
                ('Fill', models.FloatField()),
                ('Embroider', models.FloatField()),
                ('Line', models.FloatField()),
                ('Box', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Produto_base',
                'verbose_name_plural': 'Produtos_bases',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grossProfit', models.FloatField(blank=True, null=True)),
                ('unitsSold', models.IntegerField()),
                ('spentWeaving', models.FloatField()),
                ('spentClose', models.FloatField()),
                ('spentFiling', models.FloatField()),
                ('spentEmbroider', models.FloatField()),
                ('spentLine', models.FloatField()),
                ('spentBox', models.FloatField(default=0.0)),
                ('totalCost', models.FloatField()),
                ('netProfit', models.FloatField()),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Venda.product')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Produto_Custos_Base',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
