# Generated by Django 5.0.1 on 2024-02-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venda', '0004_product_product_base_cost_sale_remove_venda_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='day',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='sale',
            name='month',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='sale',
            name='spentBox',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
